package report

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/rivetron/cortex/src/domain"
	"github.com/rivetron/cortex/src/utils"
)

type MarkdownGenerator struct {
	outputDir string
}

func NewMarkdownGenerator(outputDir string) (*MarkdownGenerator, error) {
	if outputDir == "" {
		donwloadspath, err := utils.GetDownloadsPath()
		if err != nil {
			return nil, fmt.Errorf("failed to get downloads path: %w", err)
		}
		outputDir = filepath.Join(donwloadspath, "cortex-reports")
	}

	if err := utils.EnsureDirectoryExists(outputDir); err != nil {
		return nil, fmt.Errorf("failed to create output directory: %w", err)
	}

	return &MarkdownGenerator{
		outputDir: outputDir,
	}, nil
}

func (m *MarkdownGenerator) buildMarkdownContent(result *domain.ScanResult) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Subdomain Scan Report: %s\n\n", result.Domain)
	sb.WriteString("**Generated by:** Cortex\n")
	fmt.Fprintf(&sb, "**Scan Date:** %s\n", result.StartTime.Format("2006-01-02 15:04:05 MST"))
	fmt.Fprintf(&sb, "**Duration:** %s\n\n", result.Duration)

	sb.WriteString("## 📊 Summary\n\n")
	fmt.Fprintf(&sb, "- **Target Domain:** %s\n", result.Domain)
	fmt.Fprintf(&sb, "- **Total Subdomains Found:** %d\n", result.TotalFound)
	fmt.Fprintf(&sb, "- **Active Subdomains:** %d\n", result.ActiveSubs)
	fmt.Fprintf(&sb, "- **Sources Used:** %s\n", strings.Join(result.Sources, ", "))
	fmt.Fprintf(&sb, "- **Scan Duration:** %s\n\n", result.Duration)

	if len(result.Subdomains) == 0 {
		sb.WriteString("## ⚠️ No Subdomains Found\n\n")
		sb.WriteString("No subdomains were discovered for the target domain.\n\n")
		return sb.String()
	}

	activeSubdomains := make([]*domain.Subdomain, 0)
	inactiveSubdomains := make([]*domain.Subdomain, 0)

	for _, sub := range result.Subdomains {
		if sub.IsActive {
			activeSubdomains = append(activeSubdomains, sub)
		} else {
			inactiveSubdomains = append(inactiveSubdomains, sub)
		}
	}

	sort.Slice(activeSubdomains, func(i, j int) bool {
		return activeSubdomains[i].Name < activeSubdomains[j].Name
	})
	sort.Slice(inactiveSubdomains, func(i, j int) bool {
		return inactiveSubdomains[i].Name < inactiveSubdomains[j].Name
	})

	if len(activeSubdomains) > 0 {
		sb.WriteString("## ✅ Active Subdomains\n\n")
		sb.WriteString("| Subdomain | IP Addresses | CNAMEs | Source | Last Seen |\n")
		sb.WriteString("|-----------|--------------|---------|--------|----------|\n")

		for _, sub := range activeSubdomains {
			ips := strings.Join(sub.IPAddresses, ", ")
			if ips == "" {
				ips = "N/A"
			}

			cnames := strings.Join(sub.CNAMEs, ", ")
			if cnames == "" {
				cnames = "N/A"
			}

			fmt.Fprintf(&sb, "| `%s` | %s | %s | %s | %s |\n",
				sub.Name,
				ips,
				cnames,
				sub.Source,
				sub.Timestamp.Format("2006-01-02 15:04:05"))
		}
		sb.WriteString("\n")
	}

	if len(inactiveSubdomains) > 0 {
		sb.WriteString("## ❌ Inactive/Unresolved Subdomains\n\n")
		sb.WriteString("| Subdomain | Source | Discovered |\n")
		sb.WriteString("|-----------|--------|-----------|\n")

		for _, sub := range inactiveSubdomains {
			fmt.Fprintf(&sb, "| `%s` | %s | %s |\n",
				sub.Name,
				sub.Source,
				sub.Timestamp.Format("2006-01-02 15:04:05"))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## 📈 Statistics by Source\n\n")
	sourceStats := make(map[string]int)
	for _, sub := range result.Subdomains {
		sources := strings.Split(sub.Source, ", ")
		for _, source := range sources {
			sourceStats[strings.TrimSpace(source)]++
		}
	}

	sb.WriteString("| Source | Count | Percentage |\n")
	sb.WriteString("|--------|-------|------------|\n")

	for source, count := range sourceStats {
		percentage := float64(count) / float64(result.TotalFound) * 100
		fmt.Fprintf(&sb, "| %s | %d | %.1f%% |\n", source, count, percentage)
	}
	sb.WriteString("\n")

	sb.WriteString("## 🔧 Technical Details\n\n")
	fmt.Fprintf(&sb, "- **Scan Started:** %s\n", result.StartTime.Format("2006-01-02 15:04:05 MST"))
	fmt.Fprintf(&sb, "- **Scan Completed:** %s\n", result.EndTime.Format("2006-01-02 15:04:05 MST"))
	fmt.Fprintf(&sb, "- **Total Processing Time:** %s\n", result.Duration)
	fmt.Fprintf(&sb, "- **Discovery Methods:** %s\n", strings.Join(result.Sources, ", "))
	sb.WriteString("\n")

	if len(activeSubdomains) > 0 {
		sb.WriteString("## 🎯 Recommendations\n\n")
		sb.WriteString("### Security Considerations\n\n")
		sb.WriteString("- Review all active subdomains for unnecessary services\n")
		sb.WriteString("- Ensure all subdomains have proper SSL certificates\n")
		sb.WriteString("- Check for default credentials on administrative interfaces\n")
		sb.WriteString("- Implement proper access controls and monitoring\n\n")

		sb.WriteString("### Next Steps\n\n")
		sb.WriteString("- Perform security scans on active subdomains\n")
		sb.WriteString("- Review DNS configurations for potential issues\n")
		sb.WriteString("- Consider implementing subdomain monitoring\n")
		sb.WriteString("- Update security policies as needed\n\n")
	}

	sb.WriteString("---\n\n")
	sb.WriteString("*This report was generated by [Cortex](https://github.com/rivetron/cortex)*\n")
	fmt.Fprintf(&sb, "*Report generated on %s*\n", time.Now().Format("2006-01-02 15:04:05 MST"))

	return sb.String()
}

func (m *MarkdownGenerator) GenerateReport(result *domain.ScanResult) (string, error) {
	timestamp := time.Now().Format("2006-01-02")
	filename := fmt.Sprintf("subdomains-report-%s-%s.md", result.Domain, timestamp)
	filepath := filepath.Join(m.outputDir, filename)

	content := m.buildMarkdownContent(result)

	if err := os.WriteFile(filepath, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("failed to write report file: %w", err)
	}

	return filepath, nil
}
